services:
  - type: web
    name: crypto-levels-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: delta_tracker
      - key: COLLECTION_NAME
        value: monitored_scrips
